### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ramin-guliyev** [jamiemaguiredotnet/SocialOpinion-Public#20]
When I try to get single tweet I get 403. It happen both my tweet and the other user tweets

**Comment by matthiasjost** [comment]
I have the same issue @jamiemaguiredotnet 

```
System.Net.WebException
  HResult=0x80131509
  Message=The remote server returned an error: (403) Forbidden.
  Source=System.Net.Requests
  StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at SocialOpinionAPI.Core.BearerTokenRequestBuilder.GetBearerToken()
   at SocialOpinionAPI.Core.BearerTokenRequestBuilder.SendGET(String address)
   at SocialOpinionAPI.Core.BearerTokenRequestBuilder.Execute(String jsonBody)
   at SocialOpinionAPI.Clients.UsersClient.GetSingleUser(String username, String expansions, String tweet_fields, String media_fields, String poll_fields, String place_fields, String user_fields)
   at SocialOpinionAPI.Services.Users.UserService.GetUser(String username)
```

Version: nuget\packages\socialopinionapi\2.0.13\

**Comment by jamiemaguiredotnet** [comment]
Thanks. Are you both still experiencing the issue or can I close this?

**Comment by matthiasjost** [comment]
Thank you, Jamie. Actually, I missed to set up the tokens and keys correctly. It then worked perfectly.

**Comment by jamiemaguiredotnet** [comment]
Great @matthiasjost . I will close that issue.
